Add Yargs for Cli
Devcord/cordlr-cli pull request #140
Opened 2017-06-27 23:14 UTC by AlphaStyle

2017-06-27 23:29 UTC, bdbch requested changes
Do we need these arguments since these options are coming out of the cordlr.json?

2017-06-27 23:29 UTC, bdbch commented on bin/cordlr
> +          alias: 'p',
Do we need this?

2017-06-27 23:29 UTC, bdbch commented on bin/cordlr
> +        'prefix': {
Do we need this?

2017-06-27 23:29 UTC, bdbch commented on bin/cordlr
> +          alias: 't',
Do we need this?

2017-06-28 14:08 UTC, AlphaStyle commented
Removed Token, Prefix and plugins options to `start` and added `update`, `install`

2017-06-28 14:15 UTC, bdbch commented
@AlphaStyle There is now a merge conflict.
could you check that?

2017-06-28 21:38 UTC, AlphaStyle commented
A proposal to how the yargs cli can look like. Ideas or feedback ?

2017-06-29 15:18 UTC, bdbch approved these changes

2017-06-29 15:18 UTC, merged