Added Help Command
Devcord/cordlr-cli pull request #25
Opened 2016-09-14 19:32 UTC by db2k

2016-09-14 19:33 UTC, db2k commented on lib/actions/help.js
> +const commands = require('../../config/commands.json')
Maybe we can do this better later and somehow define this in the js files so the help list is created automatically

2016-09-14 19:42 UTC, Dragory commented on lib/actions/help.js
> +    for(i = 0; i < commands.length; i++) {
`i` probably shouldn't be a global variable; `let i` should be fine

2016-09-14 19:42 UTC, jamen commented
Each command will provide multiple propreties to describe the name, usage, description, etc. (whatever we want) using syntax like this:

```js
foo.command = 'foo';
foo.usage = 'foo <blah>';
// ...

function foo (bot, options) {
  // ...
}
```
We should use this information instead of a separate config.

2016-09-14 19:42 UTC, Dragory commented on lib/actions/help.js
> +      for(o = 0; o < commands[i].commands.length; o++) {
Same as above here

2016-09-14 19:43 UTC, Dragory requested changes

2016-09-14 19:44 UTC, jamen commented
Also, a not on the configurations, you should be using:
```
function (bot, options) {
  // ...
```
The `options` parameter contains the configuration provided by [`rc`](https://npmjs.org/rc), you should also define utility functions inside of there to have access to those.

2016-09-14 19:44 UTC, db2k commented
@jamen as I said, never worked with this system. Could you provide a demo on how to work with the function wrapping the run function?

I'll update this.

2016-09-14 19:45 UTC, jamen commented
I'll send a pull-request updating `role`, after I do a pull request updating docs on configuration (what is on my current working branch)

2016-09-14 19:45 UTC, Dragory commented
If the names/descriptions were part of the commands itself, maybe this would be a good reason to switch to using ES6 classes for the commands? Have the name etc. as its properties.

2016-09-14 19:46 UTC, jamen commented
ES6 classes don't have properties, only methods.  They're sugar over constructor + prototypes.  We also want to keep a functional structure.  I don't see anything wrong with the system.  Fast and clean.  :)

2016-09-14 19:53 UTC, db2k commented
@jamen you could still use getters and setters for properties, but still I don't mind as long as I can understand the concept later + it works haha.

2016-09-14 20:11 UTC, jamen commented
Merge with master.  I've changed actions folder from `cordlr/lib/actions` to `cordlr/actions`.

2016-09-14 22:12 UTC, jamen commented
Updated `roles.js`.  See that and try to mimic the style.  Let me know if you have any questions.

2016-09-15 09:35 UTC, db2k commented
I'll update this branch as soon as your role-cleanup branch is merged.

2016-09-16 07:21 UTC, closed without merging