Add loaders and remove actions.
Devcord/cordlr-cli pull request #73
Opened 2016-10-10 07:44 UTC by jamen

I've implemented this new feature in light of @seanc's ideas.  I'm calling them "loaders".  There is a page in the docs I added called ["Loaders"](https://github.com/Devcord/cordlr/blob/e3b09ed252d4f9cd7ba2bee582eff99cb5ef0c6a/docs/loader.md), you can read all about them there.

In terms of changes, loaders will be a seamless transition because everything is backwards compatible, yet adds some cool functionality.

In addition, I've cleaned up the code in general, and removed `setup` and `install` (as we are transitioning to a more simple and powerful state, rather than robust and incomplete/useless)

Additions list:
 - The `"loader"`property in your config, and module type for it.
 - CLI aliases `x`, `p`, `t`, and `l` to `prefix`, `plugins`, `token`, and `loader` respectively, and `plugin`
 - Supplying a folder scope as first argument, i.e. `cordlr foo` will load `./foo/package.json`. (This replaces actions)

Removal list:
 - `cordlr install`: it is simplest to rely on `npm install` (the user already has it).
 - `cordlr setup`: We only have `"loader"` natively now, and you can use other package.json generators.
 - `cordlr help` and `cordlr version`: Not standard, use `--help` and `--version` flags instead.

2016-10-10 07:53 UTC, jamen commented
new usage looks like this:

```js
cordlr -t ... -p cordlr-color -p cordlr-svg -p chordlr
```

2016-10-10 08:06 UTC, jamen commented
This also helps with trivial / opinionated / experimental things.  If you have an idea on how plugins should work, pop in a new loader and test it:

```js
"loader": "./my-experimental-loader"
```

2016-10-10 09:55 UTC, mees- commented
if we won't have a setup command we should maybe think about creating a yeoman generator to maintain easy setup for less experienced users

2016-10-10 10:02 UTC, mees- requested changes

2016-10-10 10:02 UTC, mees- commented on bin/cordlr
> +  if (flags.help) return help()
I agree with replacing it with the flags, i think it conforms to the standard better

2016-10-10 10:02 UTC, mees- commented on bin/loader.js
> +    bot.emit('loaded', !!plugins.length || new Error('No plugins'))
I don't think one event(name) should be used for succes and error, i think emitting an error event if no plugins are specified would be better

2016-10-10 10:02 UTC, mees- commented on bin/methods/start.js
> +  config.writeToFile = (cb) => writeFile(configPath, JSON.stringify(config, null, 2), cb)
maybe use a promise here, see #74

2016-10-10 15:29 UTC, jamen commented
I also have an idea for alternative usage in loading plugins:

```js
cordlr cordlr-color cordlr-svg chordlr -t ...
```
Instead of needing the `-p` flag.  I also don't think scoped folder is very useful.

2016-10-11 10:45 UTC, jamen commented
Branch has been updated.

2016-10-11 10:47 UTC, mees- commented on package.json
> +  "description": "A discord bot using plugins created from the community.",
Shouldn't this be `created by the community`?

2016-10-11 10:49 UTC, jamen commented on package.json
> +  "description": "A discord bot using plugins created from the community.",
Updated.

2016-10-11 10:49 UTC, mees- approved these changes
Looks good, i like the new loader idea!

2016-10-11 10:50 UTC, merged